name: Build Artifacts

on:
  push:
    branches:
      - 'gh-pages'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run test
    - run: yarn run build
    - uses: EndBug/add-and-commit@v6
      with:
        add: 'index.html'
        message: 'generate resume'
      env:
        CI: true