name: Build Artifacts

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn run test
    - run: yarn run build
    - run: git add index.html
    - uses: Automattic/action-commit-to-branch@master
      with:
        branch: gh-pages
        commit_message: 'generate resume'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}